{% set name = "sympy_equation" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sympy_equation-{{ version }}.tar.gz
  sha256: 0d4cca5b359d61b0ca97c2978042cf87f720b11c7a3fdc19243559f1c19e5edc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - param
    - sympy

test:
  imports:
    - sympy_equation
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Davide-sd/sympy-equation
  summary: Equations that can be algebraicly manipulated.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://sympy-equation.readthedocs.io

extra:
  recipe-maintainers:
    - Davide-sd
